Release 2.3.0 * changed license to GPLv3 * more refactoring * changes in configuration file * edited README and install.sh

diff --git a/sources/git-etc b/sources/git-etc
--- a/sources/git-etc
+++ b/sources/git-etc
@@ -1,13 +1,38 @@
 #!/bin/bash
+#     git-etc simple daemon written on BASH for monitoring changes in files
+#     Copyright (C) 2013 Evgeniy Alekseev
+# 
+#     This program is free software; you can redistribute it and/or modify
+#     it under the terms of the GNU General Public License as published by
+#     the Free Software Foundation; either version 3 of the License, or
+#     (at your option) any later version.
+# 
+#     This program is distributed in the hope that it will be useful,
+#     but WITHOUT ANY WARRANTY; without even the implied warranty of
+#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#     GNU General Public License for more details.
+# 
+#     You should have received a copy of the GNU General Public License
+#     along with this program; if not, see http://www.gnu.org/licenses
+#     or write to the Free Software Foundation,Inc., 51 Franklin Street,
+#     Fifth Floor, Boston, MA 02110-1301  USA
+
+# functions
+error_mes() {
+  case "$1" in
+    "config"    ) echo "[EE] Configuration file is not set";;
+    "directory" ) echo "[EE]: Directory '$2' doesn't exist";;
+    "flag"      ) echo "[EE] Unknown flag";;
+    "number"    ) echo "[EE] '$2' is not a number";;
+    "unknown"   ) echo "[EE] Unknown error";;
+  esac
+  exit 1
+}
 func_help() {
   echo -e "Simple daemon written on BASH for monitoring changes in files"
-  echo -e "\nUsage: git-etc [ --for-all ] [ -i ignore-list ] [ -h | --help ] [ -v | --version ] -d /path/to/directory -t time-to-sleep" 
-  echo -e "\nRequired parameters:"
-  echo -e "  -d  --directory   - path to GIT repository"
-  echo -e "  -t  --timesleep   - time to sleep"
-  echo -e "\nAdditional parametrs:"
-  echo -e "      --for-all     - do not change rights to .git"
-  echo -e "  -i  --ignorelist  - files in ignore list"
+  echo -e "\nUsage: git-etc [ -c | --config /etc/git-etc.conf ] [ -h | --help ] [ -v | --version ]"
+  echo -e "\nParametrs:"
+  echo -e "  -c  --config      - path to configuration file"
   echo -e "  -h  --help        - show this help and exit"
   echo -e "  -v  --version     - show version and exit"
   echo -e "\nSee \"man 1 git-etc\" for more details"
@@ -16,122 +41,89 @@ func_help() {
 func_ver() {
   echo -e "                   git-etc                   "
   echo -e "Simple daemon for monitoring changes in files"
-  echo -e "Version : 2.2.2                 License : GPL"
+  echo -e "Version : 2.3.0               License : GPLv3"
   echo -e "Author :          Evgeniy Alexeev aka arcanis"
   echo -e "E-mail :             esalexeev (at) gmail.com"
   exit 0
 }
-isnum () {
+isnum() {
     (t=$(( 0$1+0 ))) 2>/dev/null
 }
 
-FORALL="1"
+CONF_FILE="/etc/git-etc.conf"
+# parametrs parsing
 until [ -z $1 ]; do
-  if [ "$1" = "-h" ]; then
-    func_help; fi
-  if [ "$1" = "--help" ]; then
-    func_help; fi
-  if [ "$1" = "-v" ]; then
-    func_ver; fi
-  if [ "$1" = "--version" ]; then
-    func_ver; fi
-  if [ "$1" = "-d" ]; then
-    DIRECTORY="$2"
-    shift; fi
-  if [ "$1" = "--directory" ]; then
-    DIRECTORY="$2"
-    shift; fi
-  if [ "$1" = "-t" ]; then
-    TIMESLEEP="$2"
-    shift; fi
-  if [ "$1" = "--timesleep" ]; then
-    TIMESLEEP="$2"
-    shift; fi
-  if [ "$1" = "-i" ]; then
-    IGNORELIST=`echo $2 | sed -e 's/;;/ /g'`
-    shift; fi
-  if [ "$1" = "--ignorelist" ]; then
-    IGNORELIST=`echo $2 | sed -e 's/;;/ /g'`
-    shift; fi
-  if [ "$1" = "--for-all" ]; then
-    FORALL="0"; fi
+  case "$1" in
+    "-h" | "--help"    ) func_help;;
+    "-v" | "--version" ) func_ver;;
+    "-c" | "--config"  ) [ -z "$2" ] && error_mes "config" || CONF_FILE="$2" && shift;;
+    *                  ) error_mes "flag";;
+  esac
   shift
 done
+# default values
+DIRECTORY="/etc/"
+IGNORELIST="mtab;;*.Bak;;*.bak;;*.pacnew;;*.pacsave;;*.pacorig;;*.new;;*.old;;*.bckp;;ld.so.cache"
+FORALL=1
+TIMESLEEP=12
+echo "[II] Reading configuration from '$CONF_FILE'"
+[ -e "$CONF_FILE" ] || error_mes "config"
+for VAR in "$(cat "$CONF_FILE")"; do eval "$VAR"; done
+IGNORELIST=$(echo $IGNORELIST | sed -e 's/;;/ /g')
 
-if [[ -z "$DIRECTORY" || -z "$TIMESLEEP" ]]; then
-  echo "[EE]: Parametrs aren't set"
-  echo "Usage: git-etc [ --for-all ] [ -i ignore-list ] [ -h | --help ] [ -v | --version ] -d /path/to/directory -t time-to-sleep" 
-  exit 1
-fi
-
-if [ ! -d "$DIRECTORY" ]; then
-  echo "[EE]: Directory '$DIRECTORY' doesn't exist"
-  exit 1
-fi
-
-if isnum $TIMESLEEP; then
-  if [ $TIMESLEEP -ge 1 ]; then
-    echo "[II]: Set DIRECTORY to '$DIRECTORY'"
-    TIMESLEEP=$(( $TIMESLEEP*3600 ))
-    echo "[II]: Set TIMESLEEP to '$TIMESLEEP' sec"
-  else
-    echo "[EE]: '$TIMESLEEP' isn't valid number"
-    exit 1
-  fi
-else
-  echo "[EE]: '$TIMESLEEP' isn't a number"
-  exit 1
-fi
+# error check
+[ -d "$DIRECTORY" ] && echo "[II]: Set DIRECTORY to '$DIRECTORY'" || error_mess "directory" "$DIRECTORY"
+isnum "$TIMESLEEP" || error_mes "number" "$TIMESLEEP"
+[ $TIMESLEEP -ge 1 ] && TIMESLEEP=$(($TIMESLEEP*3600)) || error_mes "number" "$TIMESLEEP"
+echo "[II]: Set TIMESLEEP to '$TIMESLEEP' sec"
 
 
-# Change cwd
+# work block
+# change cwd
 cd /
-
-# Output to /dev/null
 < /dev/null > /dev/null 2>&1 &
 
-
-# Creating git repository
-GITDIR=$DIRECTORY/.git
+# creating git repository
+GITDIR="$DIRECTORY/.git"
 if [ ! -d "$GITDIR" ]; then
   echo "[II]: Creating git repository"
-  cd $DIRECTORY
+  cd "$DIRECTORY"
   git init
-  if [[ $FORALL == "1" ]]; then
+  if [[ $FORALL == 1 ]]; then
     echo "[II]: Changing rights to '$GITDIR'"
-    chmod -R o-rwx $GITDIR
+    chmod -R o-rwx "$GITDIR"
   fi
   echo "[II]: Set username and e-mail"
   git config user.name "git-etc"
   git config user.email "git-etc@mail"
   echo "[II]: Creating initial commit"
   git add -A .
-  git commit -m `date +%Y%m%d%H%M%S-%N`
+  git commit -m $(date +%Y%m%d%H%M%S-%N)
   cd /
 fi
 
-# Adding files in ignore-list
+# adding files in ignore-list
 echo "[II]: Cheching ignore-list"
 if [ -z "$IGNORELIST" ]; then
   echo "[WW]: IGNORELIST isn't set"
 else
-  for IGNORE in $( echo $IGNORELIST ); do
+  for IGNORE in $(echo $IGNORELIST); do
     label=0
-    for ITEMS in $( cat $GITDIR/info/exclude ); do
-      if [[ "$IGNORE" == $ITEMS ]]; then
+    for ITEM in $(cat "$GITDIR/info/exclude"); do
+      if [[ "$IGNORE" == "$ITEM" ]]; then
         label=1
       fi
     done
     if [[ "$label" == 0 ]]; then
-      echo "[II]: Adding $IGNORE in ignore-list"
-      echo $IGNORE >> $GITDIR/info/exclude
+      echo "[II]: Adding '$IGNORE' to ignore-list"
+      echo "$IGNORE" >> "$GITDIR/info/exclude"
     fi
   done
 fi
 
-# Creating experimental branch
-cd $DIRECTORY
-EXPERIMENTAL=`git branch | grep experimental`
+# creating experimental branch
+cd "$DIRECTORY"
+EXPERIMENTAL=$(git branch | grep experimental)
 if [ -z "$EXPERIMENTAL" ]; then
   echo "[II]: Creating experimental branch"
   git branch experimental
@@ -141,12 +133,11 @@ fi
 cd /
 
 
-
-# Forking
+# forking
 (
   while true; do
 # Creating commit
-    cd $DIRECTORY
+    cd "$DIRECTORY"
     echo "[II]: Set username and e-mail"
     git config user.name "git-etc"
     git config user.email "git-etc@mail"
@@ -156,7 +147,7 @@ cd /
     git commit -m `date +%Y%m%d%H%M%S-%N`
     cd /
 
-# Waiting $TIMESLEEP hours
+# waiting $TIMESLEEP hours
     echo "[II]: Waiting '$TIMESLEEP' sec"
     sleep $TIMESLEEP
   done
